xcode_app_path: "/Users/jruffi01/Library/Developer/Xcode/DerivedData/ShieldStreams-enojswrlbyvusrgqbpkptnufvcny/Build/Products/Debug-iphonesimulator/ShieldStreams.app"
appium-version: '1.3.0-beta1'
platformName: 'iOS'
platformVersion: '8.0'
deviceName: 'iPhone Simulator'
webdriver_url: 'http://127.0.0.1:4723/wd/hub'
