[Behaving]
test_on_infra: 'saucelabs'
build: '1.0 TF_dev'

[Appium]
webdriver_url: 'http://127.0.0.1:4723/wd/hub'
appium-version: '1.2.2'
platformName: 'iOS'
platformVersion: '7.1'
deviceName: 'iPhone'
udid: ''
app: ""

[SauceLabs]
username: ''
password: ''
api-key: ''
webdriver_url: 'http://ondemand.saucelabs.com:80/wd/hub'
appium-version: '1.3.6'
platformName: 'iOS'
platformVersion: '7.1'
deviceName: 'iPhone Simulator'
app: ''

