[Behaving]
test_on_infra: 'saucelabs'
build: '1.0 TF_dev'

[Appium]
webdriver_url: 'http://127.0.0.1:4723/wd/hub'
appium-version: '1.2.2'
platformName: 'iOS'
platformVersion: '7.1'
deviceName: 'iPhone'
udid: '93ad6bb379660203e3bcd7d9f39b8588a19175c0'
app: "/Users/jruffi01/Library/Developer/Xcode/DerivedData/ShieldStreams-enojswrlbyvusrgqbpkptnufvcny/Build/Products/Debug-iphonesimulator/ShieldStreams.app"

[SauceLabs]
username: 'jruffing_bsc'
password: '1999wasagoodyear!'
api-key: 'cc5e4e03-18a2-453b-baad-2b18c0c97296'
webdriver_url: 'http://ondemand.saucelabs.com:80/wd/hub'
appium-version: '1.2.2'
platformName: 'iOS'
platformVersion: '7.1'
deviceName: 'iPhone Simulator'
app: 'sauce-storage:vicert_shield_streams.zip'

